refactor: update sh error trap

diff --git a/backend/dockerfile b/backend/dockerfile
--- a/backend/dockerfile
+++ b/backend/dockerfile
@@ -1,10 +1,11 @@
 FROM ghcr.io/zerocluster/node/app
 
-RUN --mount=type=secret,id=GITHUB_TOKEN,env=GITHUB_TOKEN <<EOF
+RUN --mount=type=secret,id=GITHUB_TOKEN,env=GITHUB_TOKEN \
+    <<EOF
 #!/usr/bin/env bash
 
 set -Eeuo pipefail
-trap 'echo -e "⚠  Error ($0:$LINENO): $(sed -n "${LINENO}p" "$0" 2> /dev/null | grep -oE "\S.*\S|\S" || true)" >&2; return 3 2> /dev/null || exit 3' ERR
+trap 'echo "⚠  Error ($0:$LINENO): $BASH_COMMAND" && return 3 2> /dev/null || exit 3' ERR
 
 # install dependencies
 NODE_ENV=production npm install-clean
@@ -21,5 +22,4 @@ popd
 # cleanup
 script=$(curl -fsSL "https://raw.githubusercontent.com/softvisio/scripts/main/env-build-node.sh")
 bash <(echo "$script") cleanup
-
 EOF
